language: r
sudo: required
r:
    - oldrel
    - release
    - devel
r_github_packages: tidyverse/dplyr
warnings_are_errors: true
 after_success:
    - Rscript -e 'covr::codecov()'
matrix:
    include:
    - r: oldrel
    - r: release
    - r: devel
    - os: osx

