comment: false
codecov:
       token: 7df03bdd-cb2d-4087-848a-a77b4955b78f
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
      enabled: false
