on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

name: test-coverage

jobs:
  test-coverage:
    runs-on: Ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages(c("remotes","testthat", "covr","rlang"),dependencies=TRUE)
          

        shell: Rscript {0}


      - name: Install dependencies
        run:  |
          install.packages(c("remotes", "rcmdcheck"), dependencies=TRUE)
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github("r-lib/covr")
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
