on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

name: R-CMD-check-devel

jobs:
  R-CMD-check:
    runs-on: Ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"), dependencies=TRUE)
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github("r-lib/covr")
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
